export const SETLOADING = 'SETLOADING';
export const SETDEPOSITLOADING = 'SETDEPOSITLOADING';
export const SETTOKEN = 'SETTOKEN';
export const SETEMAILMODAL = 'SETEMAILMODAL';
export const SETSHOWDRAWER = 'SETSHOWDRAWER';
export const SETUSERDATA = 'SETUSERDATA';
export const SETDEPOSITMODAL = 'SETDEPOSITMODAL';